# Generated by Django 3.0.7 on 2020-07-27 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0002_auto_20200720_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('current_salary', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('about', models.CharField(blank=True, max_length=400, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('reference_name', models.CharField(blank=True, max_length=20, null=True)),
                ('reference_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reference_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.BooleanField()),
                ('mtirial_status', models.BooleanField(default=False)),
                ('birth_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('street_address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('zip', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_set_na', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SeekerSkillSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.IntegerField(default=0)),
                ('skill_set_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='job_seeker_profile.SkillSet')),
                ('user_account_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='job_seeker_profile.CV')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference_name', models.CharField(max_length=50)),
                ('reference_email', models.EmailField(max_length=254)),
                ('reference_phone', models.CharField(max_length=40)),
                ('user_account_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='job_seeker_profile.CV')),
            ],
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pdf_cv_file', models.FileField(upload_to='')),
                ('user_account_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='job_seeker_profile.CV')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current_job', models.BooleanField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('job_title', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=4000)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='job_seeker_profile.Location')),
                ('user_account_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='job_seeker_profile.CV')),
            ],
        ),
        migrations.CreateModel(
            name='EducationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_degree_name', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('institute_university_name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('complete_date', models.DateField(blank=True, null=True)),
                ('percentage', models.IntegerField(blank=True, null=True)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('website', models.CharField(blank=True, max_length=250, null=True)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='job_seeker_profile.Location')),
                ('user_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seeker_profile.CV')),
            ],
        ),
        migrations.AddField(
            model_name='cv',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='job_seeker_profile.Location'),
        ),
        migrations.AddField(
            model_name='cv',
            name='user_account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.UserAccount'),
        ),
    ]
