# Generated by Django 3.0.7 on 2020-07-28 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
        ('job_seeker_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='user_account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user_management.UserAccount', unique=True),
        ),
    ]
